### PR TITLE
ood node vnc support

### PR DESCRIPTION
**Pull request by diedpigs**

### CODE REVIEW

**Comment by jprorama** [comment]
Could you split the mount module refactor into a separate pull request.  It's not directly related to enabling the vnc support.

**Comment by diedpigs** [comment]
if we dont use mount module, we need to run `mount -a` separately. 
do you want me to put the command in playbook, or we manually run it?

**Comment by jprorama** [comment]
It's ok, that we need to run that manually for now.  We'll merge your patch for the mount refactor before the vnc support work, so it'll be in place for future use.

**Comment by jprorama** [comment]
Tested the updates and ood now has the interactive session tabs, launches the desktop job but when I click the  novnc link the vnc session won't connect. Says "Failed to connect to server".   All the VNC bits are running on c0 so I suspect it's something to do with the proxying.

**Comment by jprorama** [comment]
BTW, the merge conflict is due to the slurmd start up happening after the http config edits.  That is taken care of by the warewulf commit and should already be in vagrant-provision.   Likely should merge that onto your feature branch to catch up with the current state.

**Pull request merged**
