### PR TITLE
Feature ood user registration app

### PR DESCRIPTION
**Pull request by diedpigs**
Adding ansible tasks that installs `mod_wsgi` for httpd24 software collection, which we build and host on Fedora Copr service. Then copy `flask_user_reg` project from [Mitchell's repo](https://gitlab.rc.uab.edu/mmoo97/flask_user_reg) and put it in `/var/www/ood/register/flask_user_flask`.

I have the following variables in `group_vars/all`, which we can change later:

```
# User Registration
  enable_user_reg: false
  user_register_app: "flask_user_reg"
  user_register_app_path: "/var/www/ood/register/{{ user_register_app }}"
  user_register_app_repo: "https://gitlab.rc.uab.edu/mmoo97/flask_user_reg.git"
  mod_wsgi_pkg_name: "uab-httpd24-mod_wsgi"
```

### CODE REVIEW

**Comment by jprorama** [comment]
Applying this role and then logging in with a non-existent user shows me this error:
```
Error -- user doesn't exist: test
Run 'nginx_stage --help' to see a full list of available command line options.
```

Is there something which should be in place before running the role in order have the flask app execute?

**Comment by jprorama** [comment]
BTW, I activated this feature with:
```
ansible-playbook -c local -i /vagrant/CRI_XCBC/hosts -l `hostname` /vagrant/CRI_XCBC/site.yaml -b -t ood_user_reg
```

**Comment by diedpigs** [comment]
Some of you might 

> BTW, I activated this feature with:
> 
> ```
> ansible-playbook -c local -i /vagrant/CRI_XCBC/hosts -l `hostname` /vagrant/CRI_XCBC/site.yaml -b -t ood_user_reg
> ```

if you ran it after it's provisioned, you might need to restart `httpd24-httpd`.

**Comment by jprorama** [comment]
Yes.  Restart of httpd fixed the issue.

**Comment by jprorama** [comment]
Looks like this worked with my already provisioned ood and a restart of httpd.

When I rebuilt the ood node the ansible role for ood_firewall_services failed on httpd start.

After logging in I see this as the status of httpd:
```

**Comment by jprorama** [comment]
This looks good but let's move this PR over to our prod repo.

**Comment by jprorama** [comment]
Sorry wrong PR. :/

**Pull request merged**
