### PR TITLE
Patch slurmdbd settings

### PR DESCRIPTION
**Pull request by diedpigs**
it's actually updating mariadb settings, which is the database system that slurmdbd uses.
in the slurm accounting documentation, it recommended some innodb settings, not required though.
However, when start slurmdbd up, it will throw an error regarding the settings are not recommended which will delay the start up process for about .3 second. Not much, but will cause the next ansible task to fail. Therefore, here we update mariadb to fit slurm recommendation.

### CODE REVIEW

**Comment by jprorama** [comment]
It looks like I'm still getting an error from the sacct_mgr config task, even with the config change.
```
    ohpc: TASK [ohpc_install : load sacctmgr config] *************************************
    ohpc: fatal: [ohpc]: FAILED! => {"changed": true, "cmd": ["sacctmgr", "-i", "load", "/etc/slurm/sacctmgr-heirarchy.cfg"], "delta": "0:00:00.011973", "end": "2019-03-26 19:26:13.414053", "msg": "non-zero return code", "rc": 1, "start": "2019-03-26 19:26:13.402080", "stderr": "sacctmgr: error: slurm_persist_conn_open_without_init: failed to open persistent connection to ohpc:7031: Connection refused\nsacctmgr: error: slurmdbd: Sending PersistInit msg: Connection refused\nsacctmgr: error: Problem talking to the database: Connection refused", "stderr_lines": ["sacctmgr: error: slurm_persist_conn_open_without_init: failed to open persistent connection to ohpc:7031: Connection refused", "sacctmgr: error: slurmdbd: Sending PersistInit msg: Connection refused", "sacctmgr: error: Problem talking to the database: Connection refused"], "stdout": "", "stdout_lines": []}
```

Rerunning the ohpc_install role succeeds as it did before.  

This is the output of the slurmdbd.log, no db format complaints but an error about log file access that adds 16ms.  Doesn't seem like very long:
```
[2019-03-26T19:26:13.469] converting QOS table
[2019-03-26T19:26:13.469] Conversion done: success!
[2019-03-26T19:26:13.485] error: chdir(/var/log): Permission denied
[2019-03-26T19:26:13.485] chdir to /var/tmp
[2019-03-26T19:26:13.486] slurmdbd version 18.08.6 started
```

The permission denied error is more surprising and it is curious why the chdir to /var/tmp.  Is this really the cwd that slurmdbd should operate from?
```
[vagrant@ohpc vagrant]$ ps -ef | grep slurmdbd
slurm     9417     1  0 19:26 ?        00:00:00 /usr/sbin/slurmdbd
[vagrant@ohpc vagrant]$ sudo ls -l /proc/9417/cwd 
lrwxrwxrwx. 1 slurm slurm 0 Mar 26 19:33 /proc/9417/cwd -> /var/tmp
```

**Comment by diedpigs** [comment]
Weird, i didn't get error when i tested it before making this PR. but now i also got error. 
in `slurm.conf` we can change the log file location:
```
SlurmctldLogFile=/var/log/slurmctld.log
SlurmdDebug=3
SlurmdLogFile=/var/log/slurmd.log
```
Maybe we should create `/var/log/slurm/` and set it with write permission for slurm?

**Comment by jprorama** [comment]
Try the log location idea and lets see.

**Comment by diedpigs** [comment]
Just tested it. Create `/var/log/slurm/` and change log file path into that folder works fine. However, there's still two slurm related log file created in `/var/log`. One of them are created by ansible task, maybe upstream also had this problem, another one i am still trying to find out where it came from.

**Comment by eesaanatluri** [comment]
@jprorama @diedpigs I tested this PR. It works and can be merged.

**Pull request merged**
