### PR TITLE
WIP: Add the cluster to the Slurm DB for the slurmctld to communicate

### PR DESCRIPTION
**Pull request by eesaanatluri**

### CODE REVIEW

**Comment by eesaanatluri** [comment]
I was thinking that this would solve the issue with sacctmgr but still gave the same error ```ohpc: TASK [ohpc_install : Add cluster to DB] ****************************************
    ohpc: fatal: [ohpc]: FAILED! => {"changed": true, "cmd": ["sacctmgr", "add", "cluster", "ohpc"], "delta": "0:00:00.011412", "end": "2019-03-20 14:49:56.829709", "msg": "non-zero return code", "rc": 1, "start": "2019-03-20 14:49:56.818297", "stderr": "sacctmgr: error: slurm_persist_conn_open_without_init: failed to open persistent connection to ohpc:7031: Connection refused\nsacctmgr: error: slurmdbd: Sending PersistInit msg: Connection refused\nsacctmgr: error: Problem talking to the database: Connection refused", "stderr_lines": ["sacctmgr: error: slurm_persist_conn_open_without_init: failed to open persistent connection to ohpc:7031: Connection refused", "sacctmgr: error: slurmdbd: Sending PersistInit msg: Connection refused", "sacctmgr: error: Problem talking to the database: Connection refused"], "stdout": "", "stdout_lines": []}```

**Comment by eesaanatluri** [comment]
I checked to see if slow start up of slurmdbd is causing the issue with the cluster name not being registered with the slurm DB, the slurmdbd started immediately with and without the cluster being registered manually.

**Comment by jprorama** [comment]
So an explicit sacct_mgr add doesn't fix anything.  Have you tried to adding a sleep task as part of or after the slurmdbd startup?

**Comment by eesaanatluri** [comment]
Yes,  I tried. It worked.

**Pull request closed without merging**
