### PR TITLE
 Feature add jupyter ood

### PR DESCRIPTION
**Pull request by eesaanatluri**
Add Jupyter app to OOD.

### CODE REVIEW

**Comment by jprorama** [comment]
The install goes very smoothly and the app shows up automatically on the interactive apps list.  However, when I launch the app, it indicates startup but then the reference to the app disappears.

**Comment by jprorama** [comment]
And when I reboot my ood web service doesn't seem to come up anymore. :/

**Comment by jprorama** [comment]
I successfully (according to ansible output) applied the jupyter role to ohpc and ood.  After that I was able to see jupyter as an interactive app and launch an instance:

image

When I try to connect, however, I get this error:

image

**Comment by jprorama** [comment]
The job is running but clearly not quite right.  Here's a copy of my output log.
[output.log](https://github.com/jprorama/CRI_XCBC/files/2819225/output.log)

**Comment by jprorama** [comment]
I fixed the ohpc hostname not found error by fixing the warewulf provisioning of the /etc/hosts file on the compute node.  See #58 

Fixed the jupyter not found with an appropriate module add `module load Anaconda3`

Still getting a connection error: "Failed to connect to c0.localdomain:12735"

**Comment by jprorama** [comment]
Here's the current job output
[output(1).log](https://github.com/jprorama/CRI_XCBC/files/2819411/output.1.log)

**Comment by eesaanatluri** [comment]
Can you check your hosts file again for c0 entry. This is how it is in my env.
`10.1.1.2                c0.localdomain c0 c0-eth1.localdomain c0-eth1`

Your connection error is `Failed to connect to c0.localdomain:12735` but the URL in the image has /node/c0/12345, I expect it to be /node/c0.localdomain/12345. I wonder what's causing it to change.

**Pull request merged**
