### PR TITLE
Patch ansible yum deprecation

### PR DESCRIPTION
**Pull request by diedpigs**
Just wanted to get rid of ansible deprecated warning

### CODE REVIEW

**Comment by jprorama** [comment]
Looks like there is another place that needs this fix:
```
    ohpc: TASK [pre_ohpc : install fail2ban] *********************************************
    ohpc:  [WARNING]: Consider using the yum module rather than running 'yum'.  If you
    ohpc: need to use command because yum is insufficient you can add 'warn: false' to
    ohpc: this command task or set 'command_warnings=False' in ansible.cfg to get rid of
    ohpc: this message.
```

**Comment by jprorama** [comment]
Odd, also saw the error here:
```

**Comment by diedpigs** [comment]
so, this PR mainly focus on DEPRECATION WARNINGS which is using `yum` and `with_items` module together. All other warnings are left as it is now. Do you want me to include those as well? 

It's weird for fail2ban task since it is using yum module to install. 
```
   - name: install fail2ban # separate b/c it's in epel
     yum: name=fail2ban state=latest
```

for the checking kernel version part, we can change to use `uname -r`.

**Comment by jprorama** [comment]
Ah. Yes. I was confusing the warnings. Lets stick with the deprecation fix.  

Still find the module warning confusing.

**Pull request merged**
